# Nome do workflow - apenas uma etiqueta para identificação
name: Test Workflow

# Definindo quando o workflow deve ser acionado
on:
  # Aciona o workflow quando há um push para o branch 'main'
  push:
    branches:
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - develop
      - homologacao
      - master

# Definindo os jobs (tarefas) a serem executados
jobs:
  # Nome do job
  test_job:
    name: Executando job de teste
    # Define o ambiente onde o job será executado (Ubuntu mais recente)
    runs-on: ubuntu-latest

    # Definindo as etapas (steps) do job
    steps:
      # Primeira etapa: usar a ação 'checkout' para baixar o código do repositório
      - name: Step 1
        uses: actions/checkout@v4

      # Segunda etapa: executar um comando shell simples
      - name: Step 2
        # O comando 'echo Hello, world!' imprime "Hello, world!" no termina
        run: echo Hello, world!
